version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DEBUG: 1
    volumes:
      - ./init/localstack:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app/backend
    ports:
      - "8000:8000"
    environment:
      DB_DSN: postgresql+asyncpg://postgres:postgres@postgres:5432/app
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT_INTERNAL: http://localstack:4566
      S3_PUBLIC_ENDPOINT: http://localhost:4566
      S3_BUCKET: media
      S3_REGION: us-east-1
      S3_USE_PATH_STYLE: "true"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      HIGGSFIELD_API_KEY: ${HIGGSFIELD_API_KEY}
      HIGGSFIELD_SECRET: ${HIGGSFIELD_SECRET}
      HIGGSFIELD_BASE: https://platform.higgsfield.ai
      APP_DEBUG: "true"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app/backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      localstack:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.workers.celery_app worker --loglevel=info --concurrency=4
    working_dir: /app/backend
    environment:
      DB_DSN: postgresql+asyncpg://postgres:postgres@postgres:5432/app
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT_INTERNAL: http://localstack:4566
      S3_PUBLIC_ENDPOINT: http://localhost:4566
      S3_BUCKET: media
      S3_REGION: us-east-1
      S3_USE_PATH_STYLE: "true"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      HIGGSFIELD_API_KEY: ${HIGGSFIELD_API_KEY}
      HIGGSFIELD_SECRET: ${HIGGSFIELD_SECRET}
      HIGGSFIELD_BASE: https://platform.higgsfield.ai
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres
      - redis
      - api

volumes:
  postgres_data:
  localstack_data:

