version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_DSN: postgresql+asyncpg://postgres:postgres@postgres:5432/app
      S3_ENDPOINT_INTERNAL: ${S3_ENDPOINT_INTERNAL:-http://localstack:4566}
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT:-http://localhost:4566}
      S3_BUCKET: ${S3_BUCKET:-media}
      S3_REGION: ${S3_REGION:-us-east-1}
      S3_USE_PATH_STYLE: ${S3_USE_PATH_STYLE:-true}
      USE_PUBLIC_URLS: ${USE_PUBLIC_URLS:-true}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      HIGGSFIELD_API_KEY: ${HIGGSFIELD_API_KEY}
      HIGGSFIELD_SECRET: ${HIGGSFIELD_SECRET}
      HIGGSFIELD_BASE: https://platform.higgsfield.ai
      APP_DEBUG: "true"
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
