"""v7

Revision ID: 15cc2086f595
Revises: 5bb957311c07
Create Date: 2025-10-19 07:15:33.485379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cc2086f595'
down_revision: Union[str, Sequence[str], None] = '5bb957311c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('option_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_attachments_option_id'), 'attachments', ['option_id'], unique=False)
    op.create_foreign_key(None, 'attachments', 'options', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_index(op.f('ix_attachments_option_id'), table_name='attachments')
    op.drop_column('attachments', 'option_id')
    # ### end Alembic commands ###
