"""v3

Revision ID: 2e6012c493a9
Revises: f91128f49771
Create Date: 2025-10-18 22:57:33.021544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e6012c493a9'
down_revision: Union[str, Sequence[str], None] = 'f91128f49771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'token_usage')
    op.drop_column('messages', 'moderation')
    op.drop_column('messages', 'reply_to_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('moderation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('token_usage', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
