"""v6

Revision ID: 5bb957311c07
Revises: 71fdedafc0e1
Create Date: 2025-10-19 07:01:32.193686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb957311c07'
down_revision: Union[str, Sequence[str], None] = '71fdedafc0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_attachments_user_id'), 'attachments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'attachments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_index(op.f('ix_attachments_user_id'), table_name='attachments')
    op.drop_column('attachments', 'user_id')
    # ### end Alembic commands ###
