"""v5

Revision ID: 71fdedafc0e1
Revises: 88a0b82ee6ca
Create Date: 2025-10-19 06:44:18.342685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71fdedafc0e1'
down_revision: Union[str, Sequence[str], None] = '88a0b82ee6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('ix_attachments_user_id', table_name='attachments')
    op.drop_constraint('attachments_user_id_fkey', 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('attachments_user_id_fkey', 'attachments', 'users', ['user_id'], ['id'])
    op.create_index('ix_attachments_user_id', 'attachments', ['user_id'], unique=False)
    op.alter_column('attachments', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
