"""v4

Revision ID: 88a0b82ee6ca
Revises: 2e6012c493a9
Create Date: 2025-10-18 23:23:38.874607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a0b82ee6ca'
down_revision: Union[str, Sequence[str], None] = '2e6012c493a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attachments_sha256', table_name='attachments')
    op.drop_column('attachments', 'sha256')
    op.drop_column('attachments', 'blurhash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('blurhash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('sha256', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_attachments_sha256', 'attachments', ['sha256'], unique=False)
    # ### end Alembic commands ###
